# Generated by Django 4.2.1 on 2023-06-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalanceAdjustment',
        ),
    ]
