# Generated by Django 4.2.1 on 2023-06-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_quantity_sold_sale_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(auto_now=True),
        ),
    ]
